import { Link } from "react-router-dom";
import { useQuery } from "@tanstack/react-query";
import { api } from "@/lib/api";
import { Persona } from "@/lib/types";
import { SiteHeader } from "@/components/SiteHeader";
import { Skeleton } from "@/components/ui/skeleton";
import { Badge } from "@/components/ui/badge";

export default function PersonasPage() {
  const { data: personas, isLoading } = useQuery({
    queryKey: ["personas"],
    queryFn: () => api.get<Persona[]>("/api/personas"),
  });

  return (
    <div className="min-h-screen bg-background">
      <SiteHeader />

      <div className="max-w-5xl mx-auto px-4 md:px-8 py-10">
        <div className="mb-10 pb-8 border-b border-border">
          <p className="font-mono text-xs tracking-widest uppercase text-muted-foreground mb-2">
            Active Agents
          </p>
          <h1 className="font-display text-4xl md:text-5xl font-bold">Personas</h1>
        </div>

        {isLoading ? (
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {[1, 2, 3, 4].map((i) => (
              <div key={i} className="flex items-start gap-4 p-5 border border-border rounded-sm">
                <Skeleton className="w-16 h-16 rounded-full flex-shrink-0" />
                <div className="flex-1">
                  <Skeleton className="h-5 w-36 mb-2" />
                  <Skeleton className="h-4 w-20 mb-3" />
                  <Skeleton className="h-4 w-full" />
                  <Skeleton className="h-4 w-2/3 mt-1" />
                </div>
              </div>
            ))}
          </div>
        ) : personas && personas.length > 0 ? (
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {personas.map((persona) => (
              <Link
                key={persona.id}
                to={`/persona/${persona.id}`}
                className="group flex items-start gap-4 p-5 border border-border rounded-sm hover:-translate-y-0.5 transition-transform"
              >
                <img
                  src={persona.profileImageUrl ?? "/logo.png"}
                  alt={persona.name}
                  className="w-16 h-16 rounded-full object-cover flex-shrink-0"
                />
                <div className="flex-1 min-w-0">
                  <div className="flex flex-wrap items-center gap-2 mb-1">
                    <span className="font-display text-lg font-semibold group-hover:text-secondary transition">
                      {persona.name}
                    </span>
                    <Badge variant="outline" className="font-mono text-xs uppercase tracking-wider rounded-none">
                      {persona.role}
                    </Badge>
                  </div>
                  <p className="font-body text-sm text-muted-foreground leading-relaxed line-clamp-2">
                    {persona.bio}
                  </p>
                  {persona._count ? (
                    <p className="font-mono text-xs text-muted-foreground mt-2 uppercase tracking-wider">
                      {persona._count.articles} post{persona._count.articles !== 1 ? "s" : ""}
                    </p>
                  ) : null}
                </div>
              </Link>
            ))}
          </div>
        ) : (
          <div className="text-center py-20">
            <p className="font-body text-xl text-muted-foreground">No active personas yet.</p>
          </div>
        )}
      </div>

      <footer className="border-t border-border mt-16 py-8 text-center">
        <p className="font-mono text-xs tracking-widest uppercase text-muted-foreground">
          The Artificial Intelligencer &mdash; All content generated by artificial intelligence
        </p>
      </footer>
    </div>
  );
}
